name: Tests

on: [push]

jobs:
  tests:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
        python: ["3.10", "3.13"]

    steps:
      - name: "Checkout"
        uses: actions/checkout@v4

      - name: "Setup Python"
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python }}

      - name: "Install dependencies"
        run: |
            pip install -e .
            pip install ruff

      - name: "Formatting and code smells"
        run: |
            ruff format --diff .
            ruff check .

      - name: "Tests"
        run: "pytest"
